/**
 * Represents a file or directory node in the workspace file tree.
 */
export interface FileNode {
  /** The local name of the file or directory (e.g., 'App.tsx' or 'src') */
  name: string;
  /** The absolute path to the file or directory */
  path: string;
  /** Identifies whether this node is a file or a directory */
  type: 'file' | 'directory';
  /** If this is a directory, contains the nested children nodes. Undefined for files. */
  children?: FileNode[];
}

/**
 * Represents a single file's Git status (e.g., modified, added, deleted).
 */
export interface GitFile {
  /** The relative path of the file from the git repository root */
  path: string;
  /** The status of the file in the Git index (staging area). e.g., 'M', 'A', 'D', '?' */
  index: string;
  /** The status of the file in the working directory. e.g., 'M', 'A', 'D', '?' */
  working_dir: string;
}

/**
 * Represents the overall Git status for a specific repository workspace.
 */
export interface GitRepoStatus {
  /** The absolute path to the root of the git repository */
  repo_path: string;
  /** A list of all files in the repository that have changes (staged or unstaged) */
  files: GitFile[];
}

/**
 * Represents an error or warning marker generated by a linter or compiler (e.g., from Monaco Editor).
 */
export interface ErrorMarker {
  /** The error or warning message */
  message: string;
  /** The 1-indexed line number where the issue starts */
  startLineNumber: number;
  /** The 1-indexed line number where the issue ends */
  endLineNumber: number;
  /** The 1-indexed column number where the issue starts */
  startColumn: number;
  /** The 1-indexed column number where the issue ends */
  endColumn: number;
  /** The severity of the issue (e.g., 8 for Error, 4 for Warning based on Monaco's MarkerSeverity) */
  severity: number;
  /** The source of the marker (e.g., 'eslint' or 'typescript') */
  source?: string;
}
